### ISSUE TITLE
Pass information from Native to Unity and the opposite

### ISSUE THREAD

**Issue by ingouackaz** [samizzo/UnityNativePrototype#4]
HI @samizzo  !

I would like to know if it's possible for me to pass for example a json file from Native to Unity and from Unity to Native ?

If it's not, how could i communicate between the native and unity ?

**Comment by ingouackaz** [comment]
From Unity it seems to be here in UnityNativeInterface.mm

Unity :     public static extern void SwitchToNative();

From iOS it seems to be here in AppDelegate

iOS : - (void)switchToUnityRequested
{
    NSLog(@"Received notification SwitchToUnityRequsted");
}

**Comment by samizzo** [comment]
Well whenever you switch between Unity and native you have to call a function, so you can pass arguments to that function. You can pass whatever you want into the function. So just change the signature of the `SwitchToNative` function.
